name: AlphaCloud
favicon: null
layout_spectrum: 0.25571
typography_spectrum: 0.0982614834792912
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.75
  lightness: 0.5
  saturation: 0.9001970053650439
  rhythmicContrast: 0.5
purpose: []
